"""retirando user_id

Revision ID: 914dde86f873
Revises: 6b33618d5ed3
Create Date: 2025-12-30 13:02:19.357579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914dde86f873'
down_revision: Union[str, Sequence[str], None] = '6b33618d5ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
