"""user_id string

Revision ID: b25d93b4da20
Revises: ca84a5621cb7
Create Date: 2026-01-03 13:07:41.773846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25d93b4da20'
down_revision: Union[str, Sequence[str], None] = 'ca84a5621cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # A MÁGICA ACONTECE AQUI: "batch_alter_table"
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.BOOLEAN(),
                   type_=sa.String(),
                   existing_nullable=True)
                   
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
